spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: yash
    password: yash
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      springframework: INFO